### ISSUE TITLE
大佬可以为好狗星系添加上3IN1的震动补丁嘛，不胜感激

### ISSUE THREAD

**Issue by treeslins** [Wokann/PokemonPinballRubySapphire_CHN#1]
大佬可以为好狗星系添加上3IN1的震动补丁嘛，不胜感激

**Comment by Wokann** [comment]
看情况，目前没有这个打算。你有一定asm基础的话，可以参考我的震动代码进行移植。核心文件是这个 [https://github.com/Wokann/PokemonPinballRubySapphire_CHN/blob/main/src/00-07_087E0340_RumbleSwitch.s](https://github.com/Wokann/PokemonPinballRubySapphire_CHN/blob/main/src/00-07_087E0340_RumbleSwitch.s)
